//! v27 diagnostic probe (not a gate test).
//!
//! Answers one question against a real TPC-H `lineitem` file: which projected
//! column types are admitted by the v0 selected-decode rule? The end-to-end
//! TPC-H run reported 0% coverage on q6 even though every q6 column is
//! REQUIRED and physically INT32/INT64, which contradicts the rule as written.
//! This isolates arrow-rs from DataFusion so the answer is unambiguous.
//!
//! Requires the fixture generated by `tpchgen-cli`; skips if absent.

use parquet::arrow::arrow_reader::{
    ParquetRecordBatchReaderBuilder, RowSelection, RowSelectionPolicy, RowSelector,
};
use parquet::arrow::{ProjectionMask, selected_decode_metrics};
use std::fs::File;

const FIXTURE: &str = "/tmp/tpch_sf1/lineitem/lineitem.1.parquet";

/// A scattered selection, shaped like a real predicate rather than a few long runs.
fn scattered_selection(total_rows: usize) -> RowSelection {
    let mut selectors = Vec::new();
    let mut covered = 0usize;
    let mut i = 0usize;
    while covered < total_rows {
        let skip = 97 + (i % 13);
        let take = 3 + (i % 7);
        let skip = skip.min(total_rows - covered);
        covered += skip;
        selectors.push(RowSelector::skip(skip));
        if covered >= total_rows {
            break;
        }
        let take = take.min(total_rows - covered);
        covered += take;
        selectors.push(RowSelector::select(take));
        i += 1;
    }
    RowSelection::from(selectors)
}

fn probe(label: &str, leaves: &[usize]) {
    let file = File::open(FIXTURE).unwrap();
    let builder = ParquetRecordBatchReaderBuilder::try_new(file).unwrap();
    let total_rows: usize = builder.metadata().file_metadata().num_rows() as usize;
    let mask = ProjectionMask::leaves(builder.parquet_schema(), leaves.iter().copied());

    selected_decode_metrics::reset();
    let reader = builder
        .with_projection(mask)
        .with_batch_size(8192)
        .with_row_selection_policy(RowSelectionPolicy::Mask)
        .with_row_selection(scattered_selection(total_rows))
        .with_selected_decode(true)
        .build()
        .unwrap();

    let mut rows = 0usize;
    for batch in reader {
        rows += batch.unwrap().num_rows();
    }
    let cov = selected_decode_metrics::snapshot();
    println!(
        "PROBE {label:<34} leaves={leaves:?} rows_out={rows} \
         selected_rows={} fallback_rows={} selected_batches={} fallback_batches={} admitted={}",
        cov.selected_rows,
        cov.fallback_rows,
        cov.selected_batches,
        cov.fallback_batches,
        cov.selected_batches > 0,
    );
}

#[test]
fn probe_tpch_lineitem_admission_by_type() {
    if !std::path::Path::new(FIXTURE).exists() {
        eprintln!("fixture {FIXTURE} absent; skipping v27 probe");
        return;
    }

    // Leaf indices in `lineitem`: 0 l_orderkey INT64, 3 l_linenumber INT32,
    // 4 l_quantity INT64/DECIMAL, 5 l_extendedprice INT64/DECIMAL,
    // 6 l_discount INT64/DECIMAL, 8 l_returnflag BYTE_ARRAY,
    // 10 l_shipdate INT32/DATE.
    probe("plain INT64 (l_orderkey)", &[0]);
    probe("plain INT32 (l_linenumber)", &[3]);
    probe("DECIMAL on INT64 (l_quantity)", &[4]);
    probe("DATE on INT32 (l_shipdate)", &[10]);
    probe("two plain ints", &[0, 3]);
    probe("q6 projection", &[4, 5, 6, 10]);
    probe("with a BYTE_ARRAY (control)", &[0, 8]);
}
